apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: simplewersjs
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: simplewersjs
        env: dev
    spec:
      containers:
      - name: flask
        image: simplewersjs.azurecr.io/simplewersjs
        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP
